//! CLI program to create (or check) a repository overview in a top-level
//! `README.md` in a repository containing a rust workspace.
//!
//! The automacially generated overview contains an up-to-date representation of
//! the packages in the workspace divided into sections according to the
//! `.workspace-docs.toml` configuration file placed alongside the top-level
//! README.md file.
//!
//! Usage to update `README.md` file:
//! ```bash
//!   workspace-docs
//! ```
//!
//! Usage to check `README.md` file:
//! ```bash
//!   workspace-docs --check
//! ```
use camino::{Utf8Path, Utf8PathBuf};
use clap::Parser;
use eyre::{Result, WrapErr};
use serde::Deserialize;
use std::{collections::HashMap, fmt::Write as _, io::Write as _};

const START_MARKER: &str = "<!-- workspace-docs start -->";
const FRONTMATTER: &str =
    "<!-- This section is automatically generated by the `workspace-docs` crate. -->";
const END_MARKER: &str = "<!-- workspace-docs end -->";

#[derive(Parser, Default)]
struct Cli {
    #[arg(long)]
    /// If true, checks current docs against current workspace cargo metadata.
    ///
    /// If false, autogenerates relevant section of README.md files.
    pub check: bool,

    /// The root of the workspace (with `README.md` and `.workspace-docs.toml`).
    /// If not given the current directory is used.
    pub workspace_root: Option<Utf8PathBuf>,
}

fn get_readme_section(path: &Utf8Path) -> Result<(String, String, String)> {
    let full_readme = std::fs::read_to_string(path)?;
    let start_idx = full_readme
        .find(START_MARKER)
        .ok_or_else(|| eyre::eyre!("No start marker `{START_MARKER}` found"))?;
    let end_idx = full_readme
        .find(END_MARKER)
        .ok_or_else(|| eyre::eyre!("No end marker `{END_MARKER}` found"))?;
    if end_idx <= start_idx {
        eyre::bail!("workspace-docs end before they start");
    }
    let mut start = full_readme;
    let mut middle = start.split_off(start_idx);
    let tail = middle.split_off(end_idx - start_idx);
    Ok((start, middle, tail))
}

#[derive(Debug, PartialEq, Eq, PartialOrd, Ord)]
struct MyPackage {
    name: cargo_metadata::PackageName,
    description: Option<String>,
    // manifest_path: Utf8PathBuf,
    // relative_path: Utf8PathBuf,
    workspace_dir: Utf8PathBuf,
    // final_dir_name: String,
    section: Option<String>,
}

fn to_my_package(p: &cargo_metadata::Package, root: &Utf8Path) -> Result<MyPackage> {
    let manifest_path = p.manifest_path.clone();
    if manifest_path.file_name() != Some("Cargo.toml") {
        eyre::bail!("expected manifest_path to end with 'Cargo.toml'");
    }
    let relative_path: Utf8PathBuf = p.manifest_path.strip_prefix(&root).unwrap().into();
    let workspace_dir: Utf8PathBuf = relative_path
        .parent()
        .ok_or_else(|| eyre::eyre!("no parent"))?
        .into();
    let section = workspace_dir
        .components()
        .next()
        .map(|c| c.as_str().to_string());
    let final_dir_name: String = workspace_dir
        .file_name()
        .ok_or_else(|| eyre::eyre!("could not extract finale dir name"))?
        .into();
    if final_dir_name.as_str() != *p.name {
        tracing::warn!(
            "package name \"{}\" and dir name \"{workspace_dir}\" do not match",
            p.name
        );
    }
    Ok(MyPackage {
        name: p.name.clone(),
        description: p.description.clone(),
        // manifest_path,
        // relative_path,
        workspace_dir,
        // final_dir_name,
        section,
    })
}

fn get_packages_from_cargo(path: &Utf8Path) -> Result<Vec<MyPackage>> {
    let metadata = cargo_metadata::MetadataCommand::new()
        .current_dir(path)
        .no_deps()
        .exec()
        .unwrap();
    let mut pkgs = metadata
        .packages
        .iter()
        .map(|p| to_my_package(&p, path))
        .collect::<Result<Vec<MyPackage>>>()?;
    pkgs.sort();
    Ok(pkgs)
}

#[derive(Deserialize)]
struct Section {
    name: String,
    description: String,
}

#[derive(Deserialize)]
struct WorkspaceDocsConfig {
    section: Vec<Section>,
}

fn read_workspace_docs_toml(docs_path: &Utf8PathBuf) -> Result<Vec<Section>> {
    let full_cfg = std::fs::read_to_string(docs_path)?;
    let cfg: WorkspaceDocsConfig = toml::from_str(&full_cfg)?;
    Ok(cfg.section)
}

fn write_section<'a>(
    section: Option<&Section>,
    pkgs: impl IntoIterator<Item = &'a MyPackage>,
    outstr: &mut String,
) -> Result<()> {
    // let section_name = section
    //     .map(|x| format!("`{}/`", x.name))
    //     .unwrap_or_else(|| "workspace root".to_string());
    let markdown_start = section
        .map(|x| format!("`{}/` - ", x.name))
        .unwrap_or_else(|| "uncategorized / miscellaneous".to_string());
    let section_description = if let Some(section) = section {
        &section.description
    } else {
        ""
    };
    writeln!(outstr, "### {markdown_start}{section_description}\n")?;
    writeln!(outstr, "<details>\n")?;
    // writeln!(outstr, "<summary>Packages in {section_name}</summary>\n")?;
    for pkg in pkgs {
        let MyPackage {
            name,
            description,
            workspace_dir,
            ..
        } = pkg;
        writeln!(
            outstr,
            " - {name} ({workspace_dir}) - {}",
            description.as_ref().map(|x| x.as_str()).unwrap_or("")
        )?;
    }
    writeln!(outstr, "</details>\n")?;
    Ok(())
}

fn compute_markdown_docs(
    pkgs_by_section_name: &HashMap<Option<String>, Vec<MyPackage>>,
    sections: &[Section],
) -> Result<String> {
    let mut result = format!("{START_MARKER}\n{FRONTMATTER}\n");
    let mut done_sections = Vec::new();
    for section in sections.iter() {
        let section_key = Some(section.name.clone());
        let pkgs = pkgs_by_section_name.get(&section_key);
        if let Some(pkgs) = pkgs {
            write_section(Some(section), pkgs, &mut result)?;
        }
        done_sections.push(section.name.clone());
    }
    // Now find all packages with no section description in the toml.
    let mut orphan_pkgs = Vec::new();
    let mut pkg_sections: Vec<_> = pkgs_by_section_name.keys().collect();
    pkg_sections.as_mut_slice().sort();
    // for (section_name, pkgs) in pkgs_by_section_name.iter() {
    for section_name in pkg_sections.iter() {
        let pkgs = pkgs_by_section_name.get(section_name).unwrap();
        if let Some(section_name) = section_name {
            if done_sections.contains(section_name) {
                continue;
            }
        }
        orphan_pkgs.extend(pkgs);
    }
    // Write the other packages
    write_section(None, orphan_pkgs, &mut result)?;
    Ok(result)
}

fn main() -> Result<()> {
    env_tracing_logger::init();
    let cli = Cli::parse();

    let workspace_root = cli
        .workspace_root
        .unwrap_or_else(|| Utf8PathBuf::from_path_buf(std::env::current_dir().unwrap()).unwrap());
    tracing::debug!("Inspecting workspace root {workspace_root}");

    let readme_path = workspace_root.join("README.md");
    let (readme_start, readme_section, readme_tail) =
        get_readme_section(&readme_path).context("getting section from README.md")?;

    // Get all packages using cargo at runtime.
    let pkgs = get_packages_from_cargo(&workspace_root)?;
    let mut pkgs_by_section_name: HashMap<Option<String>, Vec<MyPackage>> = Default::default();
    for pkg in pkgs.into_iter() {
        pkgs_by_section_name
            .entry(pkg.section.clone())
            .or_insert_with(Default::default)
            .push(pkg);
    }

    // Get section descriptions from TOML file.
    let sections = read_workspace_docs_toml(&workspace_root.join(".workspace-docs.toml"))?;

    // Compute expected markdown docs
    let expected_docs = compute_markdown_docs(&pkgs_by_section_name, &sections)?;
    if readme_section != expected_docs {
        if cli.check {
            eyre::bail!("readme does not match expected docs");
        } else {
            // replace relevant section of readme.
            let new_readme = format!("{readme_start}{expected_docs}{readme_tail}");
            let mut f = std::fs::File::create(readme_path)?;
            f.write_all(new_readme.as_bytes())?;
        }
    }
    Ok(())
}
