#ifdef __linux__
  #include "/home/strawlab/Downloads/Video_Codec_SDK_11.0.10/Interface/nvEncodeAPI.h"
#elif _WIN32
  #include "C:\Users\drand\Downloads\Video_Codec_SDK_11.0.10\Video_Codec_SDK_11.0.10\Interface\nvEncodeAPI.h"
#endif

#define MARK_FIX_753(req_name) const uint32_t Fix753_##req_name = req_name;

MARK_FIX_753(NVENCAPI_VERSION);

MARK_FIX_753(NV_ENC_CAPS_PARAM_VER);
MARK_FIX_753(NV_ENC_CREATE_INPUT_BUFFER_VER);
MARK_FIX_753(NV_ENC_CREATE_BITSTREAM_BUFFER_VER);
MARK_FIX_753(NV_ENC_CREATE_MV_BUFFER_VER);
MARK_FIX_753(NV_ENC_RC_PARAMS_VER);
MARK_FIX_753(NV_ENC_CONFIG_VER);
MARK_FIX_753(NV_ENC_INITIALIZE_PARAMS_VER);
MARK_FIX_753(NV_ENC_RECONFIGURE_PARAMS_VER);
MARK_FIX_753(NV_ENC_PRESET_CONFIG_VER);
MARK_FIX_753(NV_ENC_PIC_PARAMS_VER);
MARK_FIX_753(NV_ENC_MEONLY_PARAMS_VER);
MARK_FIX_753(NV_ENC_LOCK_BITSTREAM_VER);
MARK_FIX_753(NV_ENC_LOCK_INPUT_BUFFER_VER);
MARK_FIX_753(NV_ENC_MAP_INPUT_RESOURCE_VER);
MARK_FIX_753(NV_ENC_REGISTER_RESOURCE_VER);
MARK_FIX_753(NV_ENC_STAT_VER);
MARK_FIX_753(NV_ENC_SEQUENCE_PARAM_PAYLOAD_VER);
MARK_FIX_753(NV_ENC_EVENT_PARAMS_VER);
MARK_FIX_753(NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER);
MARK_FIX_753(NV_ENCODE_API_FUNCTION_LIST_VER);
