[package]
name = "flytrax-apriltags-calibration"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre.workspace = true
base64.workspace = true
camino.workspace = true
clap.workspace = true
image.workspace = true
machine-vision-formats.workspace = true
nalgebra.workspace = true
resvg.workspace = true
serde_yaml.workspace = true
tagger.workspace = true
tracing.workspace = true
usvg.workspace = true

ads-webasm = { workspace = true, features = ["csv-widget"] }
ads-apriltag.workspace = true
braid-april-cal.workspace = true
braid-apriltag-types.workspace = true
convert-image.workspace = true
flytrax-io.workspace = true
braid-mvg.workspace = true
opencv-ros-camera.workspace = true
env_logger.workspace = true
apriltag-detection-writer.workspace = true

[dev-dependencies]
download-verify.workspace = true

[build-dependencies]
build-util.workspace = true
