braid usr/bin
braid-default-config usr/bin
braid-offline-retrack usr/bin
braid-process-video usr/bin
braid-run usr/bin
braid-show-config usr/bin
braidz-cli usr/bin
compute-flydra1-compat usr/bin
flytrax-csv-to-braidz usr/bin
fmf usr/bin
strand-cam-pylon usr/bin
strand-cam-flydratrax-pylon usr/bin
strand-cam-vimba usr/bin

# # Commented out because we do not want to distribute this library:
# libVimbaC.so usr/lib/strand-braid
