#!/bin/bash
#
# Regenerates the "launching Strand Camera from the command line" tutorial
# video against the current repo, using the hardware-free `sim` camera
# backend (see ../README.md for what this replaces and why).
#
# Requires a Linux host with ffmpeg, xdotool, Xvfb, openbox, and xterm (hard
# requirements -- this always records on its own isolated virtual display,
# never your real desktop session), plus a browser (prefers an installed
# google-chrome/chromium, falls back to firefox) -- see ../README.md for the
# full story and how to review the output.
#
# Usage:
#   ./record.sh [OUTPUT_DIR]
#
# OUTPUT_DIR defaults to a directory named 'out' next to this script. It is
# created if missing and is not, and should not be, committed to the repo.

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_NAME="strand-cam-intro"
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../../.." && pwd)
OUT_DIR=$(cd "$(dirname "${1:-$SCRIPT_DIR/out}")" && pwd)/$(basename "${1:-$SCRIPT_DIR/out}")
mkdir -p "$OUT_DIR"

# shellcheck source=../lib/session.sh
source "$SCRIPT_DIR/../lib/session.sh"

# strand-cam itself runs as a child of the xterm shell (it must, to be
# visible on screen), so session_cleanup's window-process kill won't reach
# it. Extend the trap to also stop it directly.
trap 'pkill -f "strand-cam --camera-backend sim" 2>/dev/null || true; session_cleanup' EXIT

# Prefer, in order: an explicit override, an already-installed strand-cam
# (e.g. via the .deb package) found on PATH, then finally a from-source
# build -- so a normal desktop with the package installed never triggers an
# unnecessary cargo build.
if [ -n "${STRAND_BRAID_TARGET_DIR:-}" ]; then
    TARGET_DIR="$STRAND_BRAID_TARGET_DIR"
elif command -v strand-cam >/dev/null 2>&1; then
    TARGET_DIR=$(dirname "$(command -v strand-cam)")
    echo "=== Using installed strand-cam: $TARGET_DIR/strand-cam ==="
else
    TARGET_DIR="$REPO_ROOT/target/release"
fi

if [ ! -x "$TARGET_DIR/strand-cam" ]; then
    echo "=== Building strand-cam (cargo build --release) ==="
    ( cd "$REPO_ROOT" && cargo build --release -p strand-cam )
fi
if [ ! -x "$TARGET_DIR/strand-cam" ]; then
    echo "ERROR: $TARGET_DIR/strand-cam not found after build." >&2
    exit 1
fi

STRAND_CAM_VERSION=$("$TARGET_DIR/strand-cam" --version)
echo "=== $STRAND_CAM_VERSION ==="

export DISABLE_VERSION_CHECK=1
export RUST_LOG=info
export STRAND_CAM_SIM_SPEC="$REPO_ROOT/braid/braid-sim/example-sim.toml"

# strand-cam has no env var for --camera-backend (it's CLI-only, defaulting
# to Pylon if omitted -- see ../README.md's "A note on --camera-backend
# sim"). The tutorial needs to show the plain, unqualified command a user
# with real camera hardware would actually type ("strand-cam", not
# "strand-cam --camera-backend sim"): that flag is purely an artifact of
# recording without hardware and would confuse readers about what the real
# command is. A tiny wrapper script named `strand-cam`, placed earlier on
# PATH than the real binary, silently injects --camera-backend sim while
# forwarding everything else, so the terminal only ever shows the clean
# command. This wrapper is only ever on PATH for this script's own process
# and the xterm/strand-cam it launches as children -- it cannot affect how
# strand-cam runs anywhere else on this machine, during or after this run,
# and session_cleanup deletes it (along with the rest of SESSION_WORK_DIR)
# once everything's confirmed stopped.
WRAPPER_DIR="$SESSION_WORK_DIR/bin"
mkdir -p "$WRAPPER_DIR"
cat >"$WRAPPER_DIR/strand-cam" <<EOF
#!/bin/bash
exec "$TARGET_DIR/strand-cam" --camera-backend sim "\$@"
EOF
chmod +x "$WRAPPER_DIR/strand-cam"
export PATH="$WRAPPER_DIR:$TARGET_DIR:$PATH"
BUI_URL="http://127.0.0.1:3440/"

echo "=== Starting virtual display and screen capture ==="
start_display
start_capture "$OUT_DIR/raw.mp4"

echo "=== Opening terminal and browser windows ==="
TERM_WIN=$(open_terminal)

echo "=== Command 1: launch with no --camera-name (auto-selects the first camera) ==="
type_in "$TERM_WIN" "strand-cam"
wait_for_url "$BUI_URL" || { echo "ERROR: strand-cam BUI did not come up"; exit 1; }
BROWSER_WIN=$(open_browser "$BUI_URL" "$TERM_WIN")

echo "=== Watching the live view ==="
sleep 10

echo "=== Ctrl+C ==="
log_event "Ctrl+C" 1.5
send_keys "$TERM_WIN" ctrl+c
sleep 2

echo "=== Command 2: relaunch with an explicit --camera-name ==="
type_in "$TERM_WIN" "strand-cam --camera-name simcam0"
wait_for_url "$BUI_URL" || { echo "ERROR: strand-cam BUI did not come back up"; exit 1; }

echo "=== Watching the live view again ==="
sleep 10

echo "=== Stopping capture ==="
stop_capture

echo "=== Burning in captions ==="
python3 "$SCRIPT_DIR/../lib/burn_captions.py" \
    --events "$SESSION_EVENTS_FILE" \
    --input "$OUT_DIR/raw.mp4" \
    --output "$OUT_DIR/strand-cam-intro.mp4" \
    --comment "Generated by media-utils/tutorial-video-simulation/strand-cam-intro/record.sh using $STRAND_CAM_VERSION"

echo "=== Done: $OUT_DIR/strand-cam-intro.mp4 ==="
echo "Compare it against the original before deciding it's ready; adjust the"
echo "sleep durations above and rerun if the pacing looks off."
