[package]
name = "braid-april-cal-cli"
version = "0.1.0"
edition = "2024"
description = "Create a multi-camera calibration using known intrinsics and the SQPnP algorithm"
rust-version = "1.85"

[dependencies]
eyre.workspace = true
clap.workspace = true
nalgebra.workspace = true
serde_yaml.workspace = true
tracing.workspace = true
camino.workspace = true
levenberg-marquardt.workspace = true
re_sdk.workspace = true
re_types.workspace = true
opencv-ros-camera.workspace = true
convert-image.workspace = true
image.workspace = true
chrono.workspace = true

ads-webasm = { workspace = true, features = ["csv-widget"] }
braid-april-cal.workspace = true
braid-apriltag-types.workspace = true
braid-mvg.workspace = true
strand-dynamic-frame.workspace = true
bundle-adj.workspace = true
flydra-mvg.workspace = true
env-tracing-logger.workspace = true
cam-geom.workspace = true
undistort-image.workspace = true

[dev-dependencies]
tempfile.workspace = true
zip.workspace = true
download-verify.workspace = true
tracing-test.workspace = true
