[package]
name = "braid_frontend"
version = "0.12.0-alpha.9"                       # braid release synchronized
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2021"
rust-version = "1.76"

[dependencies]
console_error_panic_hook.workspace = true
anyhow.workspace = true
log.workspace = true
wasm-logger.workspace = true
gloo-events.workspace = true
gloo-utils.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
js-sys.workspace = true
yew.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

uuid = { workspace = true, features = ["js"] }
yew-tincture.workspace = true

braid-types.workspace = true
strand-cam-bui-types.workspace = true
ads-webasm.workspace = true

[dependencies.web-sys]
workspace = true
features = [
  "Event",
  "EventSource",
  "Headers",
  "HtmlInputElement",
  "MessageEvent",
  "Request",
  "RequestCache",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
]
