"""Build the final generated Rust modules from the intermediate scratch files."""

# Get the SymPy version
import sympy
SYMPY_VERSION = sympy.__version__

# Store which Python file generated each module for attribution
GEN_FILES = {
    'opencv5': 'opencv5.py',
    'opencv4': 'opencv4.py',
    'opencv0': 'opencv0.py',
    'extrinsics_only': 'extrinsics-only.py',
}

def read_file(path):
    with open(path, 'r') as f:
        return f.read()

def write_file(path, content):
    with open(path, 'w') as f:
        f.write(content)

def clean_generated_content(content):
    """Remove the generated file header lines and section dividers."""
    lines = []
    skip_next_empty = False
    for line in content.split('\n'):
        # Skip the @generated header line
        if '@generated' in line:
            continue
        # Skip the README reference line
        if 'See geometry/bundle-adj/codegen/README.md' in line:
            continue
        # Skip the "This file is part of" header line
        if 'This file is part of' in line:
            continue
        # Skip empty lines right after header lines
        if line.strip() == '' and skip_next_empty:
            continue
        skip_next_empty = False
        if '@generated' in line:
            skip_next_empty = True
        # Skip section dividers
        if '===' in line:
            continue
        # Skip section headers
        if line.strip() in ['//camera parameters', '//points']:
            continue
        lines.append(line)
    # Remove trailing empty lines
    while lines and not lines[-1].strip():
        lines.pop()
    return '\n'.join(lines).strip()


def build_module(name, focal_params, distortion_params, cam_matrix_size,
                 has_point_jacobian=False, pt_function_name=None,
                 pt_focal_params=None, pt_desc='', header_desc='',
                 cam_extra_notes='', param_comment=''):
    """Generic builder for camera model modules.

    Args:
        name: Module name (e.g., 'opencv5')
        focal_params: Focal length parameters (e.g., "f: F," or "fx: F, fy: F,")
        distortion_params: Distortion parameters (e.g., "k1: F, k2: F, p1: F, p2: F, k3: F,")
        cam_matrix_size: Camera jacobian matrix size (e.g., "2x14")
        has_point_jacobian: Whether to include point jacobian function
        pt_function_name: Custom name for point jacobian (default: {name}_point_jacobian)
        pt_focal_params: Focal params for point jacobian (default: same as camera)
        pt_desc: Description for point jacobian
        header_desc: Main file description
        cam_extra_notes: Extra notes in camera section header
        param_comment: Inline comment for distortion params
    """
    # Read and clean camera jacobian
    cam_content = read_file(f'scratch/{name}_cam.rs')
    cam_cleaned = clean_generated_content(cam_content)

    # Build the file header
    include_location = "../src/camera_models.rs"
    if has_point_jacobian:
        include_location += " and ../src/lib.rs"

    header = f'''// @generated by sympy version {SYMPY_VERSION} -- DO NOT EDIT.
// Generated by: {GEN_FILES.get(name, name + '.py')}
// See geometry/bundle-adj/codegen/README.md for how this file is produced.
//
// {header_desc}
// It is included directly via include!() in {include_location}.
'''

    # Add opencv note for opencv4/opencv0
    if name in ['opencv4', 'opencv0']:
        header += '''//
// Note: The point jacobian for all OpenCV-style intrinsic models is handled by
// opencv_intrinsics_point_jacobian in ../src/lib.rs.
'''

    # Build camera jacobian function
    extra_notes = f"\n{cam_extra_notes}" if cam_extra_notes else ""

    # Only include 'zero' variable for single focal length parameter
    zero_line = "    let zero: F = na::convert(0.0);\n" if focal_params == "f: F," else ""

    cam_function = f'''
// camera parameters section
// Important: This function expects a {cam_matrix_size} matrix and fills it with the camera Jacobian.{extra_notes}
#[expect(clippy::too_many_arguments)]
pub(crate) fn {name}_cam_jacobian<F: na::RealField + Float>(
    {focal_params}
    {distortion_params}{param_comment}
    r_x: F, r_y: F, r_z: F,
    w_x: F, w_y: F, w_z: F,
    p_x: F, p_y: F, p_z: F,
    // j is already a {cam_matrix_size} matrix, no sub-view needed
    mut j: na::MatrixViewMut<F, na::Dyn, na::Dyn>,
) {{
{zero_line}    let one: F = na::convert(1.0);
    let two: F = na::convert(2.0);
    let three: F = na::convert(3.0);

    #[cfg_attr(any(), rustfmt::skip)]
    {{
{cam_cleaned}
    }}
}}
'''

    module_content = header + cam_function

    # Build point jacobian if needed
    if has_point_jacobian:
        pt_content = read_file(f'scratch/{name}_pt.rs')
        pt_cleaned = clean_generated_content(pt_content)

        func_name = pt_function_name or f"{name}_point_jacobian"
        pt_focal = pt_focal_params or focal_params
        # Remove underscores from distortion params for point jacobian
        pt_distortion = distortion_params.replace('_', '')

        desc_comment = f"\n//\n// {pt_desc}" if pt_desc else ""

        pt_function = f'''
// points section
// Important: This function fills a 2x3 submatrix. The caller should use
// j.view_mut(pt_start, pt_geom) where pt_geom is the appropriate slice.{desc_comment}
#[expect(clippy::too_many_arguments)]
pub(crate) fn {func_name}<F: na::RealField + Float>(
    {pt_focal}
    {pt_distortion}
    r_x: F, r_y: F, r_z: F,
    w_x: F, w_y: F, w_z: F,
    p_x: F, p_y: F, p_z: F,
    mut j: na::MatrixViewMut<F, na::Dyn, na::Dyn>,
) {{
    let one: F = na::convert(1.0);
    let two: F = na::convert(2.0);
    let three: F = na::convert(3.0);

    #[cfg_attr(any(), rustfmt::skip)]
    {{
{pt_cleaned}
    }}
}}
'''
        module_content += pt_function

    write_file(f'generated/{name}.rs', module_content)


def build_full_model_module():
    """Build the opencv5 module which contains camera parameters and points sections."""
    build_module(
        name='opencv5',
        focal_params="f: F,",
        distortion_params="k1: F, k2: F, p1: F, p2: F, k3: F,",
        cam_matrix_size="2x14",
        has_point_jacobian=True,
        pt_function_name="opencv_intrinsics_point_jacobian",
        pt_desc="""This function computes the point jacobian for all OpenCV-style intrinsic models
// (OpenCV5, OpenCV4, OpenCV0) because they share the same point jacobian structure
// (distortion affects point projection). The only difference between models is
// which distortion parameters are non-zero, but the jacobian structure is the same.""",
        header_desc="""This file contains the OpenCV5 camera model camera parameter Jacobians
// and the shared point jacobian for all OpenCV-style intrinsic models."""
    )


def build_opencv4_module():
    """Build the opencv4 module which contains camera parameters only.

    Note: The point jacobian for all OpenCV-style intrinsic models (OpenCV5, OpenCV4, "opencv0")
    is handled by opencv_intrinsics_point_jacobian in the opencv5 module.
    """
    build_module(
        name='opencv4',
        focal_params="f: F,",
        distortion_params="k1: F, k2: F, p1: F, p2: F, _k3: F,",
        param_comment="  // k3 is ignored (OpenCV4 has only 4 distortion coeffs)",
        cam_matrix_size="2x13",
        cam_extra_notes="// Note: k3 is not used in OpenCV4 (only k1,k2,p1,p2 are used), but kept for API consistency.",
        header_desc="This file contains the OpenCV4 camera model camera parameter Jacobians."
    )


def build_opencv0_module():
    """Build the opencv0 module which contains camera parameters only.

    Note: The point jacobian for all OpenCV-style intrinsic models (OpenCV5, OpenCV4, "opencv0")
    is handled by opencv_intrinsics_point_jacobian in the opencv5 module.
    """
    build_module(
        name='opencv0',
        focal_params="f: F,",
        distortion_params="_k1: F, _k2: F, _p1: F, _p2: F, _k3: F,",
        param_comment="  // all distortion params ignored (Linear has no distortion)",
        cam_matrix_size="2x9",
        cam_extra_notes="// Note: None of k1,k2,p1,p2,k3 are used in the OpenCV0 model (zero distortion), but kept for API consistency.",
        header_desc="This file contains the OpenCV0 camera model (zero distortion) camera parameter Jacobians."
    )


def build_extrinsics_only_module():
    """Build the extrinsics-only module which contains camera parameters and points sections."""
    build_module(
        name='extrinsics_only',
        focal_params="fx: F, fy: F,",
        distortion_params="k1: F, k2: F, p1: F, p2: F, k3: F,",
        cam_matrix_size="2x6",
        has_point_jacobian=True,
        pt_focal_params="fx: F, fy: F,",
        header_desc="This file contains the ExtrinsicsOnly camera model Jacobians."
    )


if __name__ == '__main__':
    build_full_model_module()
    build_opencv4_module()
    build_opencv0_module()
    build_extrinsics_only_module()
    print("Built generated modules in generated/")
