import sympy as sp
from sympy.core import Rational
from sympy.core.numbers import equal_valued
from sympy.printing import rust_code
import re

def print_header(file=None, model_name=None):
    # The `// @generated` marker is a widely recognised convention (e.g. by
    # Facebook/Meta tooling and various code-review systems) signalling that a
    # file is machine-generated and should not be hand-edited.
    header = """// @generated by sympy version %s -- DO NOT EDIT.
// See geometry/bundle-adj/codegen/README.md for how this file is produced.
""" % sp.__version__
    if model_name is not None:
        header += f"// This file is part of the {model_name} camera model Jacobians.\n"
    print(header, file=file)

def fix_rust_code(xx):
    xx = ' ' + xx + ' '

    xx = xx.replace(' 0 ',' zero ')

    xx = xx.replace(' 1 ',' one ')
    xx = xx.replace(' 1*',' one*')
    xx = xx.replace('-1 ','-one ')
    xx = xx.replace('(1 ','(one ')

    xx = xx.replace(' 2*',' two*')
    xx = xx.replace('(2*','(two*')
    # Do NOT do a blanket ' 2)' -> ' two)' replacement, since that would break
    # the i32 exponent argument of Float::powi (e.g. `Float::powi(r_x, 2)`).
    # Instead, only rewrite `2` when it appears as an additive constant
    # terminating a parenthesised sub-expression, i.e. after a ` + ` or ` - `.
    xx = re.sub(r'([+\-]) 2\)', r'\1 two)', xx)
    xx = xx.replace('-2*','-two*')
    xx = xx.replace('- 2 ','- two ')

    xx = xx.replace(' 3*',' three*')
    xx = xx.replace('(3*','(three*')
    xx = xx.replace('-3*','-three*')

    xx = xx.replace('-3_f64/2.0','-three/two')

    xx = xx.replace(', 1_f64/2.0)',')') # 'Float::sqrt(x5, 1_f64/2.0)' => 'Float::sqrt(x5)'
    xx1 = xx
    xx = re.sub(r'([\w\d_]+)\.sin\(\)', r'Float::sin(\g<1>)', xx)
    xx2 = xx
    xx = re.sub(r'([\w\d_]+)\.cos\(\)', r'Float::cos(\g<1>)', xx)
    xx3 = xx

    if xx1 != xx2:
        print("Applied sin replacement: %s => %s"%(xx1, xx2))
    if xx2 != xx3:
        print("Applied cos replacement: %s => %s"%(xx2, xx3))
    xx = re.sub(r'Float::recip\((.+), -1\)', r'Float::recip(\g<1>)', xx)
    xx4 = xx

    if xx3 != xx4:
        print("Applied recip replacement: %s => %s"%(xx3, xx4))

    xx = xx.strip()
    return xx

def compute_and_print_jacobian(resid, param_vec, file=None,title=None):
    if title is not None:
        print(f'// {title}', file=file)
    expr = resid.jacobian(param_vec)

    # The integers at the end refer to "Function Style" at https://github.com/sympy/sympy/blob/b4ce69ad5d40e4e545614b6c76ca9b0be0b98f0b/sympy/printing/rust.py#L46C3-L46C19
    user_functions={"Pow": [(lambda base, exp: equal_valued(exp, -1), "Float::recip", 4),   # 1.0/x , THIS WILL REQUIRE FIXING MANUALLY BY REMOVING THE ARG.
                (lambda base, exp: equal_valued(exp, 0.5), "Float::sqrt", 4),   # x ** 0.5 , THIS WILL REQUIRE FIXING MANUALLY BY REMOVING THE ARG.
                (lambda base, exp: equal_valued(exp, -0.5), "sqrt().recip", 2),   # 1/(x ** 0.5)
                (lambda base, exp: exp == Rational(1, 3), "cbrt", 2),    # x ** (1/3)
                (lambda base, exp: equal_valued(base, 2), "exp2", 3),    # 2 ** x
                (lambda base, exp: exp.is_integer, "Float::powi", 4),           # x ** y, for i32
                (lambda base, exp: not exp.is_integer, "Float::powf", 4)],      # x ** y, for f64
                # "sin": [(lambda base, exp: True, "Float::sin", 4)],
                }


    replacements, expr_cse = sp.cse(expr)
    for r in replacements:
        xx = rust_code(r[1], user_functions=user_functions)
        xx = fix_rust_code(xx)
        print("let %s = %s;"%(r[0], xx), file=file)

    (expr_cse,) = expr_cse
    rows, cols = sp.shape(expr_cse)
    print('//final jacobian: (shape: %d x %d)'%(rows, cols), file=file)
    for i in range(rows):
        row = expr_cse.row(i).transpose()
        for j in range(len(param_vec)):
            element = row[j]
            xx = rust_code(element, user_functions=user_functions)
            xx = fix_rust_code(xx)
            print("j[(%d,%d)] = %s;"%(i, j, xx), file=file)
