//! Bundle adjustment for multiple camera calibrations
//!
//! See the [BundleAdjuster] struct for more details.
use nalgebra::{self as na, Dyn, Owned};
use num_traits::Float;
use opencv_ros_camera::RosOpenCvIntrinsics;

mod camera_models;
pub use camera_models::CameraModelType;

// Include the generated Jacobian code from the codegen directory.
// This is generated by SymPy scripts in codegen/; see codegen/README.md for details.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/codegen/generated/opencv5.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/codegen/generated/opencv4.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/codegen/generated/opencv0.rs"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/codegen/generated/extrinsics_only.rs"
));

mod camera_parameters;
use camera_parameters::{to_cam, to_fixed_params, to_params};

#[cfg(feature = "with-rerun")]
mod ba_rerun;

type NCamsType = u8;

pub const RR_CAM_BASE_PATH: &str = "world/camera";

#[inline]
fn usize(v: NCamsType) -> usize {
    v as usize
}

#[derive(thiserror::Error, Debug, Clone)]
pub enum Error {
    #[error("inconsistent data: {0}")]
    InconsistentData(&'static str),
}

type Result<T> = std::result::Result<T, Error>;

/// Perform multi-camera bundle adjustment.
///
/// In general, this works by performing A Levenberg-Marquardt optimization that
/// minimizes the reprojection error of a set of observed 2D points in multiple
/// cameras by tuning the parameters of the camera calibrations and, in most
/// cases, the 3D world coordinate positions of the points. Several different
/// possible parameterizations are available in the variants of [ModelType].
///
/// The most important internal operations are calculation of the residual
/// errors and calculation of the Jacobian of the residuals with respect to the
/// parameters (camera calibrations and estimated 3D world coordinate
/// positions).
///
/// The number of residuals is [Self::nresid], which is twice the number of
/// observed 2D points. The number of parameters is [Self::num_cams] * the
/// number of parameters per camera (which depends on the [ModelType]) plus 3
/// times the number of 3D world points (if [Self::optimize_points] is true).
///
/// Generally speaking, the Levenberg-Marquardt optimization performs iterative
/// error minimization across `num_pts` observed 2D points by using a Jacobian
/// matrix of `num_pts`*2 rows and ``num_params` columns. The Jacobian matrix is
/// sparse because each observed 3D point only depends on the parameters of the
/// cameras that observe it and on its own 3D world coordinate position. The
/// implementation takes advantage of this sparsity to efficiently compute the
/// Jacobian and perform the optimization.
#[derive(Clone)]
pub struct BundleAdjuster<F: na::RealField + Float> {
    /// The cameras, of which there are `m`.
    ///
    /// This is updated every iteration.
    ///
    /// The values are updated every iteration, but the identity of the cameras
    /// is not changed. The identity of the cameras can be determined by
    /// [Self::cam_names].
    cams: Vec<cam_geom::Camera<F, RosOpenCvIntrinsics<F>>>,

    /// The world coordinate (3D) points, of which there are `n`.
    ///
    /// The values are updated every iteration, but the identity of the points
    /// is not changed. The identity of the points can be determined by
    /// [Self::labels3d].
    points: na::Matrix3xX<F>,

    /// number of cameras
    num_cams: NCamsType,
    /// number of unique 3D world points
    num_pts: usize,

    model_type: CameraModelType,

    /// The number of residuals
    ///
    /// This is twice the number of columns in [Self::observed].
    nresid: usize,

    /// The 2D observed points.
    ///
    /// The Jacobian matrix has the number of rows equal to twice the number of
    /// columns in this matrix.
    observed: na::Matrix2xX<F>,

    /// The index of the camera doing the observation.
    ///
    /// This contains indices into [Self::cams] (and [Self::cam_names]). This is
    /// the same length as [Self::pt_idx] and equal to the number of columns in
    /// [Self::observed].
    cam_idx: Vec<NCamsType>,

    /// The index of the 3D world point being observed.
    ///
    /// This contains indices into [Self::points] (and [Self::labels3d]). This
    /// is the same length as [Self::cam_idx] and equal to the number of columns
    /// in [Self::observed].
    pt_idx: Vec<usize>,

    /// A label for each 3D point, for example an April Tag ID number.
    ///
    /// This has the same length as the number of columns in [Self::points].
    labels3d: Vec<String>,

    /// Names of the cameras,
    ///
    /// This has the same length as the number of cameras in [Self::cams].
    pub cam_names: Vec<String>,

    /// A cache of the parameters used to build `cams` and `points`.
    ///
    /// This is updated every iteration.
    params_cache: na::DVector<F>,

    /// Camera params that are not being optimized but that are fixed.
    fixed_params: Vec<F>,

    /// Whether to optimize the 3D world points or keep them fixed.
    optimize_points: bool,

    /// Names of the columns of the Jacobian matrix, for debugging.
    params_names: Vec<String>,

    /// Abbreviated ordering of parameters to show block-structure of the
    /// Jacobian matrix, for debugging.
    params_block_names: Vec<String>,

    /// Names of the rows of the Jacobian matrix, for debugging.
    residuals_names: Vec<String>,

    optimizer_step: i64,

    #[cfg(feature = "with-rerun")]
    rerun: ba_rerun::BundleAdjusterRerun,
}

impl<F: na::RealField + Float> BundleAdjuster<F> {
    /// Create a new [BundleAdjuster].
    ///
    /// Observed points (2D, in camera pixel coordinates) are specified as a 2xN
    /// matrix `observed`. The camera and world 3D point are given as a [Vec] of
    /// N indices, `cam_idx` and `pt_idx`, respectively. The initial camera
    /// calibrations and initial world 3D point locations are specified as
    /// `cams0` and `points0`, respectively.
    #[expect(clippy::too_many_arguments)]
    pub fn new(
        observed: na::Matrix2xX<F>,
        cam_idx: Vec<NCamsType>,
        pt_idx: Vec<usize>,
        cam_names: Vec<String>,
        #[cfg(feature = "with-rerun")] cam_dims: Vec<(usize, usize)>,
        cams0: Vec<cam_geom::Camera<F, RosOpenCvIntrinsics<F>>>,
        points0: na::Matrix3xX<F>,
        labels3d: Vec<String>,
        model_type: CameraModelType,
        optimize_points: bool,
        #[cfg(feature = "with-rerun")] rec: Option<re_sdk::RecordingStream>,
    ) -> Result<Self> {
        // println!("observed:\n{}", observed.transpose());
        // dbg!(&cam_idx);
        // dbg!(&pt_idx);
        // dbg!(&cam_names);

        // println!("points0:\n{}", points0.transpose());
        // dbg!(&labels3d);

        // Validate shape of data
        let nobs = observed.ncols();
        if nobs == 0 {
            return Err(Error::InconsistentData("No observations"));
        }
        if nobs != cam_idx.len() {
            return Err(Error::InconsistentData("cam index shape"));
        }
        if nobs != pt_idx.len() {
            return Err(Error::InconsistentData("point index shape"));
        }
        if labels3d.len() != points0.ncols() {
            return Err(Error::InconsistentData("3d label shape"));
        }
        if cams0.len() != cam_names.len() {
            return Err(Error::InconsistentData("cam_names shape"));
        }
        #[cfg(feature = "with-rerun")]
        if cams0.len() != cam_dims.len() {
            return Err(Error::InconsistentData("cam_dims shape"));
        }
        let nresid = nobs * 2;

        let num_cam_params = model_type.info().num_cam_params();

        // Various data consistency checks.
        {
            // Validate that we do not have the same camera more than once at
            // the same 3D world coordinate point. Form MxN matrix where M is
            // the number of cameras and N is the number of 3D world coordinate
            // points.
            let mut visibility =
                na::OMatrix::<usize, Dyn, Dyn>::zeros(cams0.len(), points0.ncols());

            // Iterate over all observations.
            for (i, j) in cam_idx.iter().zip(pt_idx.iter()) {
                visibility[(usize(*i), *j)] += 1;
            }

            // // Sum across rows to count number of views of each point.
            // let num_views_per_point = visibility.row_sum();
            // if num_views_per_point.min() < 2 {
            //     tracing::warn!("Some 3D world points were not observed multiple times.");
            // }

            // Sum across columns to count number from each camera.
            let num_points_per_camera = visibility.column_sum();
            if num_points_per_camera.min() < 2 {
                tracing::warn!("Some cameras have not observed multiple 3D world points.");
            }
        }

        // Create initial parameter vector from initial cameras and points
        // given.
        let mut fixed_params = Vec::new();
        let (params_cache, params_names, params_block_names) = {
            let mut params_cache = Vec::new();
            let mut params_names = Vec::new();
            let mut params_block_names = Vec::new();
            for (cami, cam) in cams0.iter().enumerate() {
                let i = cam.intrinsics();
                let cam_name = &cam_names[cami];
                if model_type != CameraModelType::ExtrinsicsOnly && i.fx() != i.fy() {
                    tracing::warn!(
                        "Camera {cam_name} has fx != fy ({} != {}), but model requires fx == fy. Using fx for both.",
                        i.fx(),
                        i.fy()
                    );
                }
                let p = to_params(cam, model_type);
                debug_assert_eq!(p.len(), model_type.info().num_cam_params());
                params_cache.extend(p);
                params_names.extend(
                    (0..model_type.info().num_cam_params()).map(|i| format!("cam{cami}_{i}")),
                );
                params_block_names.push(format!("cam{cami}"));
                let fp = to_fixed_params(cam, model_type);
                debug_assert_eq!(fp.len(), model_type.info().num_fixed_params);
                fixed_params.extend(fp);
            }
            if optimize_points {
                let points_slice_flat = points0.as_slice();
                debug_assert_eq!(points_slice_flat.len(), points0.ncols() * 3);
                params_cache.extend(points_slice_flat); // This flattens the matrix in column-major order, which is what we want.
                #[expect(clippy::needless_range_loop)]
                for i in 0..points0.ncols() {
                    let label_name = &labels3d[i];
                    params_names.push(format!("{label_name}_x"));
                    params_names.push(format!("{label_name}_y"));
                    params_names.push(format!("{label_name}_z"));
                    params_block_names.push(label_name.to_string());
                }
            };
            debug_assert_eq!(params_cache.len(), params_names.len());
            let params_cache: na::DVector<F> = params_cache.into();

            if optimize_points {
                debug_assert_eq!(
                    params_cache.nrows(),
                    cams0.len() * num_cam_params + points0.ncols() * 3
                );
            } else {
                debug_assert_eq!(params_cache.nrows(), cams0.len() * num_cam_params);
            }
            (params_cache, params_names, params_block_names)
        };

        let mut residuals_names = Vec::with_capacity(nresid);
        for ((_obs, cam_idx), pt_idx) in observed
            .column_iter()
            .zip(cam_idx.iter())
            .zip(pt_idx.iter())
        {
            // let cam_name = &cam_names[usize(*cam_idx)];
            let label_name = &labels3d[*pt_idx];
            residuals_names.push(format!("cam{cam_idx}_{label_name}_dx"));
            residuals_names.push(format!("cam{cam_idx}_{label_name}_dy"));
        }

        let mut myself = Self {
            model_type,
            num_cams: cams0.len().try_into().unwrap(),
            num_pts: points0.ncols(),
            nresid,
            observed,
            cam_idx,
            pt_idx,
            cam_names,

            cams: cams0.to_vec(),
            points: points0,
            labels3d,
            params_cache: params_cache.clone(),
            fixed_params,
            optimize_points,
            params_names,
            params_block_names,
            residuals_names,
            optimizer_step: -1, // will be incremented to 0 on first call to set_params
            #[cfg(feature = "with-rerun")]
            rerun: ba_rerun::BundleAdjusterRerun {
                cam_dims,
                rec,
                did_show_rerun_warning: false,
            },
        };
        // call once to log initial data to rerun
        levenberg_marquardt::LeastSquaresProblem::set_params(&mut myself, &params_cache);
        Ok(myself)
    }

    pub fn cams(&self) -> &[cam_geom::Camera<F, RosOpenCvIntrinsics<F>>] {
        &self.cams
    }

    pub fn points(&self) -> &na::Matrix3xX<F> {
        &self.points
    }

    pub fn labels3d(&self) -> &[String] {
        &self.labels3d[..]
    }

    fn num_points_columns(&self) -> usize {
        if self.optimize_points {
            self.num_pts * 3
        } else {
            0
        }
    }

    /// Return the name of each parameter in the parameter vector, for debugging.
    pub fn params_names(&self) -> &[String] {
        &self.params_names
    }

    /// Return the names of the blocks in the parameter vector, for debugging.
    pub fn params_block_names(&self) -> &[String] {
        &self.params_block_names
    }

    /// Return the names of each residual, for debugging.
    pub fn residuals_names(&self) -> &[String] {
        &self.residuals_names
    }
}

impl<F: na::RealField + Float> levenberg_marquardt::LeastSquaresProblem<F, Dyn, Dyn>
    for BundleAdjuster<F>
{
    type ParameterStorage = Owned<F, Dyn>;
    type ResidualStorage = Owned<F, Dyn>;
    type JacobianStorage = Owned<F, Dyn, Dyn>;

    fn set_params(&mut self, x: &na::DVector<F>) {
        self.optimizer_step += 1;

        #[cfg(feature = "with-rerun")]
        {
            if let Some(rec) = &self.rerun.rec {
                rec.set_time_sequence("optimizer step", self.optimizer_step);
            }
        };

        let num_cam_params = self.model_type.info().num_cam_params();
        let num_fixed_params = self.model_type.info().num_fixed_params;

        self.params_cache = x.clone();
        debug_assert_eq!(
            x.nrows(),
            usize(self.num_cams) * num_cam_params + self.num_points_columns()
        );
        let params = x.as_slice();
        debug_assert_eq!(x.nrows(), params.len());
        let (cam_params, point_params) = params.split_at(usize(self.num_cams) * num_cam_params);
        debug_assert_eq!(point_params.len(), self.num_points_columns());

        let mut cams = Vec::with_capacity(self.cams.len());
        for (i, params) in cam_params.chunks_exact(num_cam_params).enumerate() {
            let fixed_params = if num_fixed_params == 0 {
                &[]
            } else {
                let start = i * num_fixed_params;
                let stop = (i + 1) * num_fixed_params;
                &self.fixed_params[start..stop]
            };
            let cam = to_cam(params, self.model_type, fixed_params);
            cams.push(cam);
        }

        let points = if self.optimize_points {
            na::Matrix3xX::from_column_slice(point_params)
        } else {
            self.points.clone()
        };

        #[cfg(feature = "with-rerun")]
        if let Some(rec) = &self.rerun.rec {
            // Log points.
            let pts: Vec<[f32; 3]> = points
                .column_iter()
                .map(|v| {
                    [
                        v.x.to_f32().unwrap(),
                        v.y.to_f32().unwrap(),
                        v.z.to_f32().unwrap(),
                    ]
                })
                .collect();
            rec.log(
                "/",
                &re_sdk_types::archetypes::Points3D::new(&pts).with_labels(self.labels3d.clone()),
            )
            .unwrap();

            // For each camera
            for ((cam, cam_name), cam_dims) in cams
                .iter()
                .zip(self.cam_names.iter())
                .zip(self.rerun.cam_dims.iter())
            {
                // Log pinhole in rerun 3D space.
                use braid_mvg::rerun_io::AsRerunTransform3D;
                let base_path = format!("{RR_CAM_BASE_PATH}/{cam_name}");
                let extrinsics = cam.extrinsics();
                rec.log(
                    base_path.as_str(),
                    &ba_rerun::extrinsics_f64(&extrinsics)
                        .as_rerun_transform3d()
                        .into(),
                )
                .unwrap();
                let raw_path = format!("{base_path}/raw");
                let (w, h) = cam_dims;

                let i = cam.intrinsics();
                if i.skew().to_f64().unwrap().abs() > 1e-15 {
                    tracing::warn!("Camera has skew, but rerun cameras do not support skew");
                }
                if !i.distortion.is_linear() {
                    if !self.rerun.did_show_rerun_warning {
                        tracing::warn!(
                            "Showing distorted 2D data in rerun but rerun cannot transform 3D data to distorted 2D coordinates. See https://github.com/rerun-io/rerun/issues/2499"
                        );
                        self.rerun.did_show_rerun_warning = true;
                    }
                }
                let intrinsics_linear: cam_geom::IntrinsicParametersPerspective<_> =
                    cam_geom::PerspectiveParams {
                        fx: i.fx(),
                        fy: i.fy(),
                        skew: na::convert(0.0),
                        cx: i.cx(),
                        cy: i.cy(),
                    }
                    .into();
                let pinhole = braid_mvg::rerun_io::cam_geom_to_rr_pinhole_archetype(
                    &intrinsics_linear,
                    *w,
                    *h,
                )
                .unwrap();
                rec.log(raw_path.as_str(), &pinhole).unwrap();

                // Log reprojections in rerun 2D space.
                let mut xy: Vec<(f32, f32)> = vec![];
                let mut labels: Vec<String> = vec![];
                let mut vecs: Vec<(f32, f32)> = vec![];
                for ((obs, cam_idx), pt_idx) in self
                    .observed
                    .column_iter()
                    .zip(self.cam_idx.iter())
                    .zip(self.pt_idx.iter())
                {
                    let this_cam_name = &self.cam_names[usize(*cam_idx)];
                    if this_cam_name != cam_name {
                        continue;
                    }

                    let pt = self.points.column(*pt_idx);
                    let label = &self.labels3d[*pt_idx];
                    let pts = cam_geom::Points::new(pt.transpose());
                    let predicted = cam.world_to_pixel(&pts).data.transpose();
                    xy.push((
                        predicted[(0, 0)].to_f32().unwrap(),
                        predicted[(1, 0)].to_f32().unwrap(),
                    ));
                    labels.push(label.clone());

                    let delta = obs - predicted;
                    vecs.push((
                        delta[(0, 0)].to_f32().unwrap(),
                        delta[(1, 0)].to_f32().unwrap(),
                    ));
                }

                let ent_path = format!("{raw_path}/predicted");
                rec.log(
                    ent_path.as_str(),
                    &re_sdk_types::archetypes::Points2D::new(&xy).with_labels(labels),
                )
                .unwrap();

                let ent_path = format!("{raw_path}/delta");
                rec.log(
                    ent_path.as_str(),
                    &re_sdk_types::archetypes::Arrows2D::from_vectors(vecs).with_origins(xy),
                )
                .unwrap();
            }
        }

        self.cams = cams;
        self.points = points;
    }

    fn params(&self) -> na::DVector<F> {
        self.params_cache.clone()
    }

    fn residuals(&self) -> Option<na::DVector<F>> {
        // println!("Step: {}", self.optimizer_step);
        let mut residuals = Vec::with_capacity(self.nresid);
        for ((obs, cam_idx), pt_idx) in self
            .observed
            .column_iter()
            .zip(self.cam_idx.iter())
            .zip(self.pt_idx.iter())
        {
            let cam = &self.cams[usize(*cam_idx)];
            let pt = self.points.column(*pt_idx);
            let pts = cam_geom::Points::new(pt.transpose());
            let predicted = cam.world_to_pixel(&pts).data.transpose();
            let diff = obs - predicted;
            if false {
                let tag_id = &self.labels3d[*pt_idx];
                println!(
                    "  cam: {cam_idx}, point: {tag_id}, observed: ({:.1},{:.1}), proj: ({:.1},{:.1}), dxdy: ({:.1},{:.1}), dist: {:.1}",
                    obs.x,
                    obs.y,
                    predicted.x,
                    predicted.y,
                    diff.x,
                    diff.y,
                    Float::sqrt(diff.x * diff.x + diff.y * diff.y)
                );
            }
            residuals.push(diff.x);
            residuals.push(diff.y);
        }
        debug_assert_eq!(residuals.len(), self.nresid);
        let residuals = na::DVector::from_column_slice(&residuals);
        // println!("{}", residuals);
        Some(residuals)
    }

    /// Compute jacobian matrix with respect to camera parameters and 3D world
    /// points.
    ///
    /// The jacobian has shape (nresid, num_cams * num_cam_params +
    /// num_points_params) where `num_points_params` is the number of parameters
    /// for the 3D world points. If `optimize_points` is true,
    /// `num_points_params` is `num_pts
    /// * 3`, otherwise it is 0.
    ///
    /// In general this jacobian is sparse.
    fn jacobian(&self) -> Option<na::Matrix<F, Dyn, Dyn, Self::JacobianStorage>> {
        let num_cam_params = self.model_type.info().num_cam_params();
        let mut j = na::OMatrix::<F, Dyn, Dyn>::zeros(self.nresid, self.params_cache.len());

        // Iterate over all observed points.
        for (obs_idx, (cam_idx, pt_idx)) in self.cam_idx.iter().zip(self.pt_idx.iter()).enumerate()
        {
            // we have 2 entries in the residual vector per observation
            let ridx = obs_idx * 2;

            // Identify the sub-matrix for the camera parameters.
            let cam_start = (ridx, usize(*cam_idx) * num_cam_params);
            let cam_geom = (2, num_cam_params);

            // Identify the sub-matrix for the 3D world coordinate point.
            let pt_col = usize(self.num_cams) * num_cam_params + pt_idx * 3;
            let pt_start = (ridx, pt_col);
            let pt_geom = (2, 3);
            // Compute jacobian for these camera parameters and world point.
            self.model_type.eval_cam_jacobians(
                self,
                *cam_idx,
                *pt_idx,
                &mut j,
                (cam_start, cam_geom),
            );
            if self.optimize_points {
                self.eval_pt_jacobians(*cam_idx, *pt_idx, &mut j, (pt_start, pt_geom));
            }
        }
        Some(j)
    }
}

impl<F: na::RealField + Float> BundleAdjuster<F> {
    /// Evaluate jacobian with respect to world points
    fn eval_pt_jacobians(
        &self,
        cam_num: NCamsType,
        pt_num: usize,
        j: &mut na::OMatrix<F, Dyn, Dyn>,
        pt_sub: ((usize, usize), (usize, usize)),
    ) {
        match self.model_type {
            CameraModelType::ExtrinsicsOnly => {
                self.eval_pt_jacobians_extrinsics_only(cam_num, pt_num, j, pt_sub)
            }
            _ => self.eval_pt_jacobians_intrinsics(cam_num, pt_num, j, pt_sub),
        }
    }

    /// Jacobian w.r.t. the 3D world point for the extrinsics-only model.
    ///
    /// The symbolic expression below is produced by the SymPy script
    /// `codegen/extrinsics-only.py` (see `codegen/README.md`).
    fn eval_pt_jacobians_extrinsics_only(
        &self,
        cam_num: NCamsType,
        pt_num: usize,
        j: &mut na::OMatrix<F, Dyn, Dyn>,
        pt_sub: ((usize, usize), (usize, usize)),
    ) {
        // We pull the 3D point from self.points because we have already set this from the parameter vec.
        let pt = self.points.column(pt_num);
        let [p_x, p_y, p_z] = [pt.x, pt.y, pt.z];

        let cam = &self.cams[usize(cam_num)];
        let i = cam.intrinsics();
        let fx = i.fx();
        let fy = i.fy();
        let _cx = i.cx();
        let _cy = i.cy();
        let d = i.distortion.opencv_vec().as_slice();
        let [k1, k2, p1, p2, k3] = [d[0], d[1], d[2], d[3], d[4]];

        let e = cam.extrinsics();
        let rquat = e.pose().rotation;
        let abc = rquat.scaled_axis();
        let cc = e.camcenter();
        let [r_x, r_y, r_z] = [abc.x, abc.y, abc.z];
        let [w_x, w_y, w_z] = [cc.x, cc.y, cc.z];

        // jacobian for world point
        let (pt_start, pt_geom) = pt_sub;
        let j = j.view_mut(pt_start, pt_geom);
        debug_assert_eq!(j.nrows(), 2);
        debug_assert_eq!(j.ncols(), 3);
        extrinsics_only_point_jacobian(
            fx, fy, k1, k2, p1, p2, k3, r_x, r_y, r_z, w_x, w_y, w_z, p_x, p_y, p_z, j,
        );
    }

    /// Jacobian w.r.t. the 3D world point for the OpenCV-style intrinsics
    /// models (OpenCV5, OpenCV4, OpenCV0).
    ///
    /// All OpenCV-style intrinsic models share the same point jacobian structure
    /// (distortion affects point projection). The only difference between models
    /// is which distortion parameters are non-zero, but the jacobian structure
    /// is the same.
    ///
    /// The symbolic expression below is produced by the SymPy script
    /// `codegen/full-model.py` (see `codegen/README.md`).
    fn eval_pt_jacobians_intrinsics(
        &self,
        cam_num: NCamsType,
        pt_num: usize,
        j: &mut na::OMatrix<F, Dyn, Dyn>,
        pt_sub: ((usize, usize), (usize, usize)),
    ) {
        // We pull the 3D point from self.points because we have already set this from the parameter vec.
        let pt = self.points.column(pt_num);
        let [p_x, p_y, p_z] = [pt.x, pt.y, pt.z];

        let cam = &self.cams[usize(cam_num)];
        let i = cam.intrinsics();
        let f = i.fx(); // we checked in the constructor that fx == fy
        let _cx = i.cx();
        let _cy = i.cy();
        let d = i.distortion.opencv_vec().as_slice();
        let [k1, k2, p1, p2, k3] = [d[0], d[1], d[2], d[3], d[4]];

        let e = cam.extrinsics();
        let rquat = e.pose().rotation;
        let abc = rquat.scaled_axis();
        let cc = e.camcenter();
        let [r_x, r_y, r_z] = [abc.x, abc.y, abc.z];
        let [w_x, w_y, w_z] = [cc.x, cc.y, cc.z];

        // jacobian for world point
        let (pt_start, pt_geom) = pt_sub;
        let j_pt = j.view_mut(pt_start, pt_geom);
        debug_assert_eq!(j_pt.nrows(), 2);
        debug_assert_eq!(j_pt.ncols(), 3);
        opencv_intrinsics_point_jacobian(
            f, k1, k2, p1, p2, k3, r_x, r_y, r_z, w_x, w_y, w_z, p_x, p_y, p_z, j_pt,
        );
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_full_bundle_adjustment() {
        let points = na::Matrix3xX::<f64>::from_column_slice(&[
            1.0, 2.0, 3.0, 4.0, 5.0, 6.0, //  7.0, 8.0, 9.0,
            10.0, 11.0, 12.0,
        ]);

        let labels3d: Vec<String> = (0..points.ncols()).map(|i| format!("pt {i}")).collect();

        // Compute observed 2D points for each camera using full OpenCV5 model (including distortion).
        let cam_params = [
            // f, cx, cy, k1, radial1, radial2, tangential1, tangential2, radial3, rx, ry, rz, wx, wy, wz
            [
                1.0, 2.0, 3.0, 0.01, 0.001, -0.01, -0.001, 0.0001, 0.0, 1.0, 0.0, 7.0, 8.0, 9.0,
            ],
            // [
            //     1.1, 2.1, 3.1, 0.01, 0.001, -0.01, -0.001, 0.0001, 0.0, 0.0, 1.0, 7.1, 8.1, 9.1,
            // ],
            // [
            //     1.2, 2.2, 3.2, 0.01, 0.001, -0.01, -0.001, 0.0001, 0.0, 0.4, 0.5, 7.2, 8.2, 9.2,
            // ],
        ];
        let cams: Vec<_> = cam_params
            .iter()
            .map(|p| to_cam(p, CameraModelType::OpenCV5, &[]))
            .collect();
        let cam_names: Vec<_> = cams
            .iter()
            .enumerate()
            .map(|(i, _cam)| format!("Cam {i}"))
            .collect();
        #[cfg(feature = "with-rerun")]
        let cam_dims: Vec<_> = cams.iter().map(|_cam| (640, 480)).collect();

        let mut observed_raw = vec![];
        let mut cam_idx = vec![];
        let mut pt_idx = vec![];

        for ipt_idx in 0..points.ncols() {
            let point = points.column(ipt_idx);
            for (icam_idx, cam) in cams.iter().enumerate() {
                let pts = cam_geom::Points::new(point.transpose());
                let observed = cam.world_to_pixel(&pts).data;
                observed_raw.push(observed.x);
                observed_raw.push(observed.y);
                cam_idx.push(icam_idx.try_into().unwrap());
                pt_idx.push(ipt_idx);
            }
        }

        let observed = na::Matrix2xX::from_column_slice(&observed_raw);
        let noisy = &observed + standard_normal(observed.nrows(), observed.ncols());

        // let mut jacobian_results = vec![];
        let mut all_jacobians_approx_equal = true;

        for optimize_points in [true, false] {
            for model_type in clap::ValueEnum::value_variants() {
                println!(
                    "Testing model type: {model_type:?}, optimize 3d world point locations: {optimize_points}"
                );
                let ba = BundleAdjuster::<f64>::new(
                    noisy.clone(),
                    cam_idx.clone(),
                    pt_idx.clone(),
                    cam_names.clone(),
                    #[cfg(feature = "with-rerun")]
                    cam_dims.clone(),
                    cams.clone(),
                    points.clone(),
                    labels3d.clone(),
                    *model_type,
                    optimize_points,
                    #[cfg(feature = "with-rerun")]
                    None,
                )
                .unwrap();

                // Test that numerical differentiation matches result from jacobian.
                {
                    let mut ba = ba.clone();
                    use levenberg_marquardt::LeastSquaresProblem;

                    let jacobian_numerical =
                        levenberg_marquardt::differentiate_numerically(&mut ba).unwrap();
                    let jacobian_trait = ba.jacobian().unwrap();
                    // TODO: re-enable this
                    // approx::assert_relative_eq!(jacobian_numerical, jacobian_trait, epsilon = 1e-7);
                    let approx_equal =
                        approx::relative_eq!(jacobian_numerical, jacobian_trait, epsilon = 1e-7);
                    // jacobian_results.push((model_type, approx_equal, jacobian_numerical, jacobian_trait));
                    if !approx_equal {
                        println!(
                            "  Jacobian mismatch for model type: {model_type:?}, optimize_points: {optimize_points}"
                        );
                        println!("  Numerical Jacobian:\n    {:?}", jacobian_numerical);
                        println!("  Trait Jacobian:\n    {:?}", jacobian_trait);
                        all_jacobians_approx_equal = false;
                    }
                }

                let (_result, report) = levenberg_marquardt::LevenbergMarquardt::new().minimize(ba);
                println!("  Levenberg-Marquardt report:\n    {:?}", report);
                assert!(report.termination.was_successful());
                // TODO: check that the result is closer to the original parameters.
            }
        }
        if !all_jacobians_approx_equal {
            panic!("Jacobian mismatch for at least one model type. See above for details.");
        }
    }

    fn standard_normal<Real: na::RealField>(
        nrows: usize,
        ncols: usize,
    ) -> na::OMatrix<Real, Dyn, Dyn> {
        use rand::{SeedableRng, distributions::Distribution};

        let normal = rand_distr::Normal::new(0.0, 1.0).expect("creating normal");
        let mut rng = rand::rngs::StdRng::seed_from_u64(123456);
        na::OMatrix::from_fn_generic(na::Dyn(nrows), na::Dyn(ncols), |_row, _col| {
            na::convert::<f64, Real>(normal.sample(&mut rng))
        })
    }

    #[test]
    fn test_extrinsics_only_camera_parameters() {
        // intrinsics - linear
        let fx = 800.0;
        let fy = 820.0;
        let cx = 320.0;
        let cy = 240.0;
        // intrinsics - distortion
        let k1 = 0.01;
        let k2 = 0.001;
        let p1 = -0.002;
        let p2 = 0.0005;
        let k3 = 0.0;

        // extrinsics
        let rx = 0.1;
        let ry = 0.4;
        let rz = -0.2;
        let wx = 1.0;
        let wy = 0.5;
        let wz = -2.0;

        // 3d point
        let px = 0.3;
        let py = -0.7;
        let pz = 5.0;

        // observed 2d point
        let u = 305.0;
        let v = 198.0;

        let observed = na::Matrix2xX::from_column_slice(&[u, v]);
        let cam_idx = vec![0];
        let pt_idx = vec![0];
        let cam_names = vec!["Cam 0".to_string()];

        #[cfg(feature = "with-rerun")]
        let cam_dims: Vec<(usize, usize)> = vec![(640, 480)];

        let cam_params = &[rx, ry, rz, wx, wy, wz];
        let fixed_params = &[fx, fy, cx, cy, k1, k2, p1, p2, k3];

        let model_type = CameraModelType::ExtrinsicsOnly;
        let cam0 = to_cam(cam_params, model_type, fixed_params);

        let cams = vec![cam0];

        let points = na::Matrix3xX::<f64>::from_column_slice(&[px, py, pz]);
        let labels3d = vec!["pt 0".to_string()];

        let projected = cams[0]
            .world_to_pixel(&cam_geom::Points::new(points.transpose()))
            .data;
        print!("Observed point: {observed}");
        print!("Projected point: {projected}");

        let diff = &observed.transpose() - projected;
        print!("Difference between observed and projected: {diff}");

        let optimize_points = false;
        let ba = BundleAdjuster::<f64>::new(
            observed,
            cam_idx,
            pt_idx,
            cam_names,
            #[cfg(feature = "with-rerun")]
            cam_dims,
            cams,
            points.clone(),
            labels3d,
            model_type,
            optimize_points,
            #[cfg(feature = "with-rerun")]
            None,
        )
        .unwrap();
        let r = levenberg_marquardt::LeastSquaresProblem::residuals(&ba).unwrap();
        print!("Residuals: {r}");

        let j = levenberg_marquardt::LeastSquaresProblem::jacobian(&ba).unwrap();
        println!("{:?}", ba.params_names());
        print!("Jacobian: {j}");

        let r = r.data.as_vec();
        let diff = diff.data.as_vec();
        assert_eq!(r.len(), diff.len());
        assert_eq!(r.len(), 2);
        approx::assert_relative_eq!(r[0], diff[0], epsilon = 1e-6);
        approx::assert_relative_eq!(r[1], diff[1], epsilon = 1e-6);

        // Compare with known good values computed externally.
        approx::assert_relative_eq!(j[(0, 0)], 62.758782, epsilon = 1e-6);
        approx::assert_relative_eq!(j[(0, 1)], -868.827040, epsilon = 1e-6);
        approx::assert_relative_eq!(j[(0, 2)], -194.626133, epsilon = 1e-6);
        approx::assert_relative_eq!(j[(0, 3)], 122.249236, epsilon = 1e-6);
        approx::assert_relative_eq!(j[(0, 4)], 23.629356, epsilon = 1e-6);
        approx::assert_relative_eq!(j[(0, 5)], 16.275670, epsilon = 1e-6);

        approx::assert_relative_eq!(j[(1, 0)], 908.971740, epsilon = 1e-6);
        approx::assert_relative_eq!(j[(1, 1)], 154.613985, epsilon = 1e-6);
        approx::assert_relative_eq!(j[(1, 2)], -41.189174, epsilon = 1e-6);
        approx::assert_relative_eq!(j[(1, 3)], -36.912150, epsilon = 1e-6);
        approx::assert_relative_eq!(j[(1, 4)], 123.729704, epsilon = 1e-6);
        approx::assert_relative_eq!(j[(1, 5)], 17.519591, epsilon = 1e-6);
        println!("spot checks passed for extrinsics-only jacobian");
    }
}
