/// Statically defined arrays of the enums.

// Arguably these arrays do not belong in a -sys crate, but it is convenient to keep them alongside
// the definitions.

use super::defs::{fc2VideoMode, fc2FrameRate, fc2PixelFormat, fc2BayerTileFormat,
                  fc2Mode, fc2PropertyType};

pub static MODES: [fc2Mode; 32] = [fc2Mode::FC2_MODE_0,
                                   fc2Mode::FC2_MODE_1,
                                   fc2Mode::FC2_MODE_2,
                                   fc2Mode::FC2_MODE_3,
                                   fc2Mode::FC2_MODE_4,
                                   fc2Mode::FC2_MODE_5,
                                   fc2Mode::FC2_MODE_6,
                                   fc2Mode::FC2_MODE_7,
                                   fc2Mode::FC2_MODE_8,
                                   fc2Mode::FC2_MODE_9,
                                   fc2Mode::FC2_MODE_10,
                                   fc2Mode::FC2_MODE_11,
                                   fc2Mode::FC2_MODE_12,
                                   fc2Mode::FC2_MODE_13,
                                   fc2Mode::FC2_MODE_14,
                                   fc2Mode::FC2_MODE_15,
                                   fc2Mode::FC2_MODE_16,
                                   fc2Mode::FC2_MODE_17,
                                   fc2Mode::FC2_MODE_18,
                                   fc2Mode::FC2_MODE_19,
                                   fc2Mode::FC2_MODE_20,
                                   fc2Mode::FC2_MODE_21,
                                   fc2Mode::FC2_MODE_22,
                                   fc2Mode::FC2_MODE_23,
                                   fc2Mode::FC2_MODE_24,
                                   fc2Mode::FC2_MODE_25,
                                   fc2Mode::FC2_MODE_26,
                                   fc2Mode::FC2_MODE_27,
                                   fc2Mode::FC2_MODE_28,
                                   fc2Mode::FC2_MODE_29,
                                   fc2Mode::FC2_MODE_30,
                                   fc2Mode::FC2_MODE_31];

pub static VIDEO_MODES: [fc2VideoMode; 23] = [fc2VideoMode::FC2_VIDEOMODE_160x120YUV444,
                                              fc2VideoMode::FC2_VIDEOMODE_320x240YUV422,
                                              fc2VideoMode::FC2_VIDEOMODE_640x480YUV411,
                                              fc2VideoMode::FC2_VIDEOMODE_640x480YUV422,
                                              fc2VideoMode::FC2_VIDEOMODE_640x480RGB,
                                              fc2VideoMode::FC2_VIDEOMODE_640x480Y8,
                                              fc2VideoMode::FC2_VIDEOMODE_640x480Y16,
                                              fc2VideoMode::FC2_VIDEOMODE_800x600YUV422,
                                              fc2VideoMode::FC2_VIDEOMODE_800x600RGB,
                                              fc2VideoMode::FC2_VIDEOMODE_800x600Y8,
                                              fc2VideoMode::FC2_VIDEOMODE_800x600Y16,
                                              fc2VideoMode::FC2_VIDEOMODE_1024x768YUV422,
                                              fc2VideoMode::FC2_VIDEOMODE_1024x768RGB,
                                              fc2VideoMode::FC2_VIDEOMODE_1024x768Y8,
                                              fc2VideoMode::FC2_VIDEOMODE_1024x768Y16,
                                              fc2VideoMode::FC2_VIDEOMODE_1280x960YUV422,
                                              fc2VideoMode::FC2_VIDEOMODE_1280x960RGB,
                                              fc2VideoMode::FC2_VIDEOMODE_1280x960Y8,
                                              fc2VideoMode::FC2_VIDEOMODE_1280x960Y16,
                                              fc2VideoMode::FC2_VIDEOMODE_1600x1200YUV422,
                                              fc2VideoMode::FC2_VIDEOMODE_1600x1200RGB,
                                              fc2VideoMode::FC2_VIDEOMODE_1600x1200Y8,
                                              fc2VideoMode::FC2_VIDEOMODE_1600x1200Y16];

pub static ALL_VIDEO_MODES: [fc2VideoMode; 26] = [fc2VideoMode::FC2_VIDEOMODE_160x120YUV444,
                                                  fc2VideoMode::FC2_VIDEOMODE_320x240YUV422,
                                                  fc2VideoMode::FC2_VIDEOMODE_640x480YUV411,
                                                  fc2VideoMode::FC2_VIDEOMODE_640x480YUV422,
                                                  fc2VideoMode::FC2_VIDEOMODE_640x480RGB,
                                                  fc2VideoMode::FC2_VIDEOMODE_640x480Y8,
                                                  fc2VideoMode::FC2_VIDEOMODE_640x480Y16,
                                                  fc2VideoMode::FC2_VIDEOMODE_800x600YUV422,
                                                  fc2VideoMode::FC2_VIDEOMODE_800x600RGB,
                                                  fc2VideoMode::FC2_VIDEOMODE_800x600Y8,
                                                  fc2VideoMode::FC2_VIDEOMODE_800x600Y16,
                                                  fc2VideoMode::FC2_VIDEOMODE_1024x768YUV422,
                                                  fc2VideoMode::FC2_VIDEOMODE_1024x768RGB,
                                                  fc2VideoMode::FC2_VIDEOMODE_1024x768Y8,
                                                  fc2VideoMode::FC2_VIDEOMODE_1024x768Y16,
                                                  fc2VideoMode::FC2_VIDEOMODE_1280x960YUV422,
                                                  fc2VideoMode::FC2_VIDEOMODE_1280x960RGB,
                                                  fc2VideoMode::FC2_VIDEOMODE_1280x960Y8,
                                                  fc2VideoMode::FC2_VIDEOMODE_1280x960Y16,
                                                  fc2VideoMode::FC2_VIDEOMODE_1600x1200YUV422,
                                                  fc2VideoMode::FC2_VIDEOMODE_1600x1200RGB,
                                                  fc2VideoMode::FC2_VIDEOMODE_1600x1200Y8,
                                                  fc2VideoMode::FC2_VIDEOMODE_1600x1200Y16,
                                                  fc2VideoMode::FC2_VIDEOMODE_FORMAT7,
                                                  fc2VideoMode::FC2_NUM_VIDEOMODES,
                                                  fc2VideoMode::FC2_VIDEOMODE_FORCE_32BITS];

pub static FRAME_RATES: [fc2FrameRate; 8] = [fc2FrameRate::FC2_FRAMERATE_1_875,
                                             fc2FrameRate::FC2_FRAMERATE_3_75,
                                             fc2FrameRate::FC2_FRAMERATE_7_5,
                                             fc2FrameRate::FC2_FRAMERATE_15,
                                             fc2FrameRate::FC2_FRAMERATE_30,
                                             fc2FrameRate::FC2_FRAMERATE_60,
                                             fc2FrameRate::FC2_FRAMERATE_120,
                                             fc2FrameRate::FC2_FRAMERATE_240];

pub static ALL_FRAME_RATES: [fc2FrameRate; 11] = [fc2FrameRate::FC2_FRAMERATE_1_875,
                                                  fc2FrameRate::FC2_FRAMERATE_3_75,
                                                  fc2FrameRate::FC2_FRAMERATE_7_5,
                                                  fc2FrameRate::FC2_FRAMERATE_15,
                                                  fc2FrameRate::FC2_FRAMERATE_30,
                                                  fc2FrameRate::FC2_FRAMERATE_60,
                                                  fc2FrameRate::FC2_FRAMERATE_120,
                                                  fc2FrameRate::FC2_FRAMERATE_240,
                                                  fc2FrameRate::FC2_FRAMERATE_FORMAT7,
                                                  fc2FrameRate::FC2_NUM_FRAMERATES,
                                                  fc2FrameRate::FC2_FRAMERATE_FORCE_32BITS];

pub static PIXEL_FORMATS: [fc2PixelFormat; 19] = [fc2PixelFormat::FC2_PIXEL_FORMAT_MONO8,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_411YUV8,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_422YUV8,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_444YUV8,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_RGB8,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_MONO16,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_RGB16,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_S_MONO16,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_S_RGB16,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_RAW8,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_RAW16,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_MONO12,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_RAW12,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_BGR,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_BGRU,
                                                  // 		FC2_PIXEL_FORMAT_RGB
                                                  // 			= FC2_PIXEL_FORMAT_RGB8,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_RGBU,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_BGR16,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_BGRU16,
                                                  fc2PixelFormat::FC2_PIXEL_FORMAT_422YUV8_JPEG];

pub static ALL_PIXEL_FORMATS: [fc2PixelFormat; 21] =
    [fc2PixelFormat::FC2_PIXEL_FORMAT_MONO8,
     fc2PixelFormat::FC2_PIXEL_FORMAT_411YUV8,
     fc2PixelFormat::FC2_PIXEL_FORMAT_422YUV8,
     fc2PixelFormat::FC2_PIXEL_FORMAT_444YUV8,
     fc2PixelFormat::FC2_PIXEL_FORMAT_RGB8,
     fc2PixelFormat::FC2_PIXEL_FORMAT_MONO16,
     fc2PixelFormat::FC2_PIXEL_FORMAT_RGB16,
     fc2PixelFormat::FC2_PIXEL_FORMAT_S_MONO16,
     fc2PixelFormat::FC2_PIXEL_FORMAT_S_RGB16,
     fc2PixelFormat::FC2_PIXEL_FORMAT_RAW8,
     fc2PixelFormat::FC2_PIXEL_FORMAT_RAW16,
     fc2PixelFormat::FC2_PIXEL_FORMAT_MONO12,
     fc2PixelFormat::FC2_PIXEL_FORMAT_RAW12,
     fc2PixelFormat::FC2_PIXEL_FORMAT_BGR,
     fc2PixelFormat::FC2_PIXEL_FORMAT_BGRU,
     // 		FC2_PIXEL_FORMAT_RGB			= FC2_PIXEL_FORMAT_RGB8, /*< 24 bit RGB. */
     fc2PixelFormat::FC2_PIXEL_FORMAT_RGBU,
     fc2PixelFormat::FC2_PIXEL_FORMAT_BGR16,
     fc2PixelFormat::FC2_PIXEL_FORMAT_BGRU16,
     fc2PixelFormat::FC2_PIXEL_FORMAT_422YUV8_JPEG,
     fc2PixelFormat::FC2_NUM_PIXEL_FORMATS,
     fc2PixelFormat::FC2_UNSPECIFIED_PIXEL_FORMAT];

pub static ALL_BAYER_TILE_FORMAT: [fc2BayerTileFormat; 6] =
    [fc2BayerTileFormat::FC2_BT_NONE,
     fc2BayerTileFormat::FC2_BT_RGGB,
     fc2BayerTileFormat::FC2_BT_GRBG,
     fc2BayerTileFormat::FC2_BT_GBRG,
     fc2BayerTileFormat::FC2_BT_BGGR,
     fc2BayerTileFormat::FC2_BT_FORCE_32BITS];

pub static ALL_PROPERTY_TYPE: [fc2PropertyType; 20] =
    [fc2PropertyType::FC2_BRIGHTNESS,
     fc2PropertyType::FC2_AUTO_EXPOSURE,
     fc2PropertyType::FC2_SHARPNESS,
     fc2PropertyType::FC2_WHITE_BALANCE,
     fc2PropertyType::FC2_HUE,
     fc2PropertyType::FC2_SATURATION,
     fc2PropertyType::FC2_GAMMA,
     fc2PropertyType::FC2_IRIS,
     fc2PropertyType::FC2_FOCUS,
     fc2PropertyType::FC2_ZOOM,
     fc2PropertyType::FC2_PAN,
     fc2PropertyType::FC2_TILT,
     fc2PropertyType::FC2_SHUTTER,
     fc2PropertyType::FC2_GAIN,
     fc2PropertyType::FC2_TRIGGER_MODE,
     fc2PropertyType::FC2_TRIGGER_DELAY,
     fc2PropertyType::FC2_FRAME_RATE,
     fc2PropertyType::FC2_TEMPERATURE,
     fc2PropertyType::FC2_UNSPECIFIED_PROPERTY_TYPE,
     fc2PropertyType::FC2_PROPERTY_TYPE_FORCE_32BITS];
