name: Build FMF CLI app

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmf-cli-app-ubuntu-22-04:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: media-utils/fmf/fmf-cli
    steps:
      - uses: actions/checkout@v6
      - name: Build FMF CLI app
        run: |
          cargo build --release
      - name: Generate THIRD-PARTY-LICENSES
        run: |
          cargo install cargo-bundle-licenses --locked
          cargo bundle-licenses --format yaml --prefer MIT --output "${{ github.workspace }}/target/release/THIRD-PARTY-LICENSES.yml"
      - uses: actions/upload-artifact@v6
        with:
          name: fmf-ubuntu
          path: |
            ${{ github.workspace }}/target/release/fmf
            ${{ github.workspace }}/target/release/THIRD-PARTY-LICENSES.yml

  fmf-cli-app-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: media-utils/fmf/fmf-cli
    steps:
      - uses: actions/checkout@v6
      - name: Build FMF CLI app
        run: |
          cargo build --release
      - name: Generate THIRD-PARTY-LICENSES
        run: |
          cargo install cargo-bundle-licenses --locked
          cargo bundle-licenses --format yaml --prefer MIT --output "${{ github.workspace }}/target/release/THIRD-PARTY-LICENSES.yml"
        shell: pwsh
      - uses: actions/upload-artifact@v6
        with:
          name: fmf-windows
          path: |
            ${{ github.workspace }}/target/release/fmf.exe
            ${{ github.workspace }}/target/release/THIRD-PARTY-LICENSES.yml

  fmf-cli-app-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: media-utils/fmf/fmf-cli
    steps:
      - uses: actions/checkout@v6
      - name: Build FMF CLI app
        run: |
          cargo build --release
      - name: Generate THIRD-PARTY-LICENSES
        run: |
          cargo install cargo-bundle-licenses --locked
          cargo bundle-licenses --format yaml --prefer MIT --output "${{ github.workspace }}/target/release/THIRD-PARTY-LICENSES.yml"
      - uses: actions/upload-artifact@v6
        with:
          name: fmf-mac
          path: |
            ${{ github.workspace }}/target/release/fmf
            ${{ github.workspace }}/target/release/THIRD-PARTY-LICENSES.yml
